### ISSUE TITLE
Mockup Erstellen

### ISSUE THREAD

**Issue by lera005** [bbzblit/insimodus#10]
# Description
Es soll ein Mockup erstellt werden für die Webseite. 
Dafür sind folgende Seiten vorgesehen: 
         - Dashboard
         - Transaktionen
         - Zahlungen erfassen

# Definition of Done:
- Überschaubares Dashboard
- Einfache Seite um Transaktionen zu erfassen.

# Epic
- #14 

# Dependencies (Issues):
- keine

**Comment by Yanni8** [comment]
Die Mockups wurden im Projektteam geteilt und abgelegt.

![image](https://github.com/user-attachments/assets/9c8f99cc-b726-4a74-ac7d-92abcb677f06)
