### ISSUE TITLE
Projekt Initialisierung

### ISSUE THREAD

**Issue by Yanni8** [bbzblit/insimodus#22]
# Description
Die Applikation sollte mittels VueJS und TailwindCSS umgesetzt und lauffähig sein.

# Definition of Done:
- Die Applikation kann mit node gestartet werden.
- TailwindCSS wird in der Applikation verwendet.
- Die Applikation läuft bei allen Teammitgliedern fehlerfrei.
- Dockerfile repräsentiert die aktuelle Applikation

# Epic
- #14 

# Dependencies (Issues):
- Keine

**Comment by codingluke** [comment]
Ich sehe die verlinkung in der history, schön wäre es gewesen auch direkt zu verlinken.

![Image](https://github.com/user-attachments/assets/da326ae8-7946-4d9a-a323-651c669b3e34)
